REM Lista dei vari repo con versioni per BuildSystem
SET SCRIPT_UPDATER=git-updater.bat

REM 11-4

SET GIT_ROOT=C:\GIT-11-4
SET BRANCH_TO_CHECKOUT=develop
CALL %SCRIPT_UPDATER% %GIT_ROOT% %BRANCH_TO_CHECKOUT% 

SET GIT_ROOT=C:\GIT-11-4-beta
SET BRANCH_TO_CHECKOUT=develop
CALL %SCRIPT_UPDATER% %GIT_ROOT% %BRANCH_TO_CHECKOUT% 

SET GIT_ROOT=C:\GIT-11-10
SET BRANCH_TO_CHECKOUT=develop
CALL %SCRIPT_UPDATER% %GIT_ROOT% %BRANCH_TO_CHECKOUT% 

SET GIT_ROOT=C:\GIT-11-10-beta
SET BRANCH_TO_CHECKOUT=develop
CALL %SCRIPT_UPDATER% %GIT_ROOT% %BRANCH_TO_CHECKOUT% 

PAUSE