ECHO "Filename:" %0 1>&2

SET BATCH_ROOT_MOUNTPOINT=Z:\GIT
IF NOT [%ROOT_MOUNTPOINT%] == [] SET BATCH_ROOT_MOUNTPOINT=%ROOT_MOUNTPOINT%

SET BATCH_ROOT_MOUNTPOINT_COMMON=Z:\GIT
IF NOT [%ROOT_MOUNTPOINT_COMMON%] == [] SET BATCH_ROOT_MOUNTPOINT_COMMON=%ROOT_MOUNTPOINT_COMMON%

rem ------------------------------------------------------------------------

SET SLN_DEVICEDRIVER=%BATCH_ROOT_MOUNTPOINT_COMMON%\TheDarkKnightDeviceDriver\TheDarkKnightDeviceDriver.sln
SET CONFIGURATION=TDK11-4

"%PATH_MSBUILD%" "%SLN_DEVICEDRIVER%" /P:CONFIGURATION=%CONFIGURATION% /T:Clean,Rebuild /P:PLATFORM=x86

rem PAUSE
