ECHO "Filename:" %0 1>&2

SET BATCH_ROOT_MOUNTPOINT=Z:\GIT
IF NOT [%ROOT_MOUNTPOINT%] == [] SET BATCH_ROOT_MOUNTPOINT=%ROOT_MOUNTPOINT%

SET BATCH_ROOT_MOUNTPOINT_COMMON=Z:\GIT
IF NOT [%ROOT_MOUNTPOINT_COMMON%] == [] SET BATCH_ROOT_MOUNTPOINT_COMMON=%ROOT_MOUNTPOINT_COMMON%

SET CONFIGURATION_INTERNAL=TDK11-4
IF NOT [%CONFIGURATION%] == [] SET CONFIGURATION_INTERNAL=%CONFIGURATION%

rem ------------------------------------------------------------------------

SET SLN_DEVICEDRIVER=%BATCH_ROOT_MOUNTPOINT_COMMON%\TheDarkKnightDeviceDriver\TheDarkKnightDeviceDriver.sln

"%BATCH_FOLDER%\bin\nuget.exe" restore "%SLN_DEVICEDRIVER%"

"%PATH_MSBUILD%" "%SLN_DEVICEDRIVER%" /P:CONFIGURATION=%CONFIGURATION_INTERNAL% /T:Clean,Rebuild /P:PLATFORM=x86  || SET BUILD_ERROR=1