ECHO "Filename:" %0 1>&2

SET VERSIONE_INTERNAL=11.4.0.0
IF NOT [%VERSIONE%] == [] SET VERSIONE_INTERNAL=%VERSIONE%

SET VERSIONE_EXTENDED_INTERNAL=11.4.0.0-master
IF NOT [%VERSIONE_EXTENDED%] == [] SET VERSIONE_EXTENDED_INTERNAL=%VERSIONE_EXTENDED%

SET INTERNAL_ROOT_MOUNTPOINT=Z:\GIT
IF NOT [%ROOT_MOUNTPOINT%] == [] SET INTERNAL_ROOT_MOUNTPOINT=%ROOT_MOUNTPOINT%

SET OUTPUT_DIR=%INTERNAL_ROOT_MOUNTPOINT%\BuildSystem\artifacts\EXE\%VERSIONE_INTERNAL%
IF NOT [%VB6_OUTPUT%] == [] SET OUTPUT_DIR=%VB6_OUTPUT%

SET INTERNAL_STANDALONE=1
IF NOT [%STANDALONE%] == [] SET INTERNAL_STANDALONE=%STANDALONE%

REM ------------------------------------------------

IF [%INTERNAL_STANDALONE%] == [1] NET USE Z: \\VBOXSRV\C_DRIVE

SET OVERLORD_DIR=%INTERNAL_ROOT_MOUNTPOINT%\OVERLORD
SET OVERLORD_CONFIGURATORE=%INTERNAL_ROOT_MOUNTPOINT%\ConfiguratoreOverlord
SET VB6PROG="C:\Program Files (x86)\Microsoft Visual Studio\VB98\VB6.EXE"

SET OVERLORD_OUTDIR=%OUTPUT_DIR%
SET OVERLORD_FILENAME=%OVERLORD_OUTDIR%\FTCONTROLSMANAGER.EXE

SET OVERLORDCONFIGURATORE_OUTDIR=%OUTPUT_DIR%
SET OVERLORDCONFIGURATORE_FILENAME=%OVERLORDCONFIGURATORE_OUTDIR%\FTCONTROLSMANAGERCONFIGURATOR.EXE

SET OUT_ERRORLOG_OVERLORD="%INTERNAL_ROOT_MOUNTPOINT%\BuildSystem\src\log\VB6MAKE_ERRORLOG_OVERLORD.TXT"
SET OUT_ERRORLOG_OVERLORDCONFIGURATORE="%INTERNAL_ROOT_MOUNTPOINT%\BuildSystem\src\log\VB6MAKE_ERRORLOG_CONFIGURATORE.TXT"

SET STAMPVER_DIR=%INTERNAL_ROOT_MOUNTPOINT%\BuildSystem\src\bin\STAMPVER.EXE

if not exist "%OVERLORD_OUTDIR%" mkdir "%OVERLORD_OUTDIR%"
if not exist "%OVERLORDCONFIGURATORE_OUTDIR%" mkdir "%OVERLORDCONFIGURATORE_OUTDIR%"

%VB6PROG% /make "%OVERLORD_DIR%\FTControlsManager.vbp" /out %OUT_ERRORLOG_OVERLORD% /outdir "%OVERLORD_OUTDIR%" 

"%STAMPVER_DIR%" -f"%VERSIONE_INTERNAL%" %OVERLORD_FILENAME%

%VB6PROG% /make "%OVERLORD_CONFIGURATORE%\FTControlsManagerConfigurator.vbp" /out %OUT_ERRORLOG_OVERLORDCONFIGURATORE% /outdir "%OVERLORDCONFIGURATORE_OUTDIR%"

"%STAMPVER_DIR%" -f"%VERSIONE_INTERNAL%" %OVERLORDCONFIGURATORE_FILENAME%

IF [%INTERNAL_STANDALONE%] == [1] NET USE Z: /DELETE

IF [%INTERNAL_STANDALONE%] == [1] PAUSE