ECHO "Filename:" %0 1>&2

SET FTCM_VERSIONE=1.1.1.1
SET TDK_VERSIONE=1.1.1.1

IF NOT [%VERSIONE%] == [] SET FTCM_VERSIONE=%VERSIONE%
IF NOT [%VERSIONE%] == [] SET TDK_VERSIONE=%VERSIONE%

SET BATCH_ROOT_MOUNTPOINT=Z:\GIT
IF NOT [%ROOT_MOUNTPOINT%] == [] SET BATCH_ROOT_MOUNTPOINT=%ROOT_MOUNTPOINT%

REM ------------------------------------------------

SET BATCH_FOLDER_VERSIONE=%BATCH_ROOT_MOUNTPOINT%\BuildSystem\src
SET RFID_VERSIONE=1.3.0
SET FTCM_SYS_FOLDER=C:\FTSYSTEM\BIN

SET FTCM_TEMPLATE_INI_FOLDER=%BATCH_ROOT_MOUNTPOINT%\BuildSystem\artifacts\TEMPLATE-INI-FTCONTROLMANAGER
SET FTCM_EXE_DESTINATION_FOLDER=%BATCH_ROOT_MOUNTPOINT%\BuildSystem\artifacts\Exe\%FTCM_VERSIONE%
SET TDK_DESTINATION_FOLDER=%BATCH_ROOT_MOUNTPOINT%\BuildSystem\artifacts\TheDarkKnight\%TDK_VERSIONE%
SET RFID_DESTINATION_FOLDER=%BATCH_ROOT_MOUNTPOINT%\BuildSystem\artifacts\Rfid\%RFID_VERSIONE%

if not exist "%TDK_DESTINATION_FOLDER%" mkdir "%TDK_DESTINATION_FOLDER%"
if not exist "%FTCM_EXE_DESTINATION_FOLDER%" mkdir "%FTCM_EXE_DESTINATION_FOLDER%"

CALL "%BATCH_FOLDER_VERSIONE%\movers\copy-FTCMDLL.bat" %FTCM_SYS_FOLDER%, %TDK_DESTINATION_FOLDER%, %RFID_DESTINATION_FOLDER%, %FTCM_EXE_DESTINATION_FOLDER%, %FTCM_TEMPLATE_INI_FOLDER%, %FTCM_VERSIONE%