ECHO "Filename:" %0 1>&2
REM ---------------------------------------RFID----------------------------------- 

@ECHO Now working on Main-Target[%MAIN_TARGET_INTERNAL%]

REM RIPULISCE LA DIRECTORY DI DESTINAZIONE RFID
@ECHO Cleaning folder ["%RFID_DESTINATION_FOLDER%"]
DEL /F /Q "%RFID_DESTINATION_FOLDER%\*.*"

REM COPIA LE DLL E TLB PER RFID
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.DLL" %RFID_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.PDB" %RFID_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.VB6.DLL" %RFID_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.VB6.PDB" %RFID_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.VB6.TLB" %RFID_DESTINATION_FOLDER%

REM ---------------------------------------DLL DI TDK----------------------------------- 

REM RIPULISCE LA DIRECTORY DI DESTINAZIONE THE DARK KNIGHT
@ECHO Cleaning folder ["%TDK_DESTINATION_FOLDER%"]
DEL /F /Q "%TDK_DESTINATION_FOLDER%\*.*"

REM COPIA TUTTE LE ALTRE DLL E TLB

COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Cameras.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Cameras.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Cameras.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Cameras.Data.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Checksum.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Checksum.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.CompositionInterface.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.CompositionInterface.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Cryptography.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Cryptography.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Exceptions.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Exceptions.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.IoC.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.IoC.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Linq.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Linq.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Log.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Log.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Styles.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Styles.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Core.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Core.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Core.Collectors.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Core.Collectors.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.WorkflowEngine.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.WorkflowEngine.PDB" %TDK_DESTINATION_FOLDER%

IF %MAIN_TARGET_INTERNAL% == 11-10 (
	COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Data.dll" %TDK_DESTINATION_FOLDER%
	COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Data.PDB" %TDK_DESTINATION_FOLDER%

	COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.MessageContracts.VB6.dll" %TDK_DESTINATION_FOLDER%
	COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.MessageContracts.VB6.PDB" %TDK_DESTINATION_FOLDER%
)

COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.BarcodeScanner.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.BarcodeScanner.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Channels.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Channels.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Modbus.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Modbus.PDB" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Modbus.Test.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Modbus.Test.PDB" %TDK_DESTINATION_FOLDER%


COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.C1911.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.C1911.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.EX700MB.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.EX700MB.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Data.PDB" %TDK_DESTINATION_FOLDER%

rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Business.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Business.VB6.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Data.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Business.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Data.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Persistence.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Presentation.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.XlsxReport.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.XlsxReport.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.XlsxReport.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.XlsxReport.Data.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Persistence.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.VB6Bridge.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.VB6Bridge.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Business.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Data.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Persistence.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.PDB" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.VB6.PDB" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Alarms.Presentation.VB6.tlb " %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.BarcodeScanner.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Business.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.VB6Bridge.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%

IF %MAIN_TARGET_INTERNAL% == 11-10 (
	COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.MessageContracts.VB6.TLB" %TDK_DESTINATION_FOLDER%
)

COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.StateMachines.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.StateMachines.PDB" %TDK_DESTINATION_FOLDER%

REM ----------------------------------- Assembly per gestione UWF ----------------------------------- 
COPY "%FTCM_SYS_FOLDER%\UWFLib.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FTLibIpc.dll" %TDK_DESTINATION_FOLDER%

REM -----------------------------------EXE FTCONTROLSMANAGER E FTCONROLSMANAGERCONFIGURATORE----------------------------------- 

REM RIPULISCE LA DIRECTORY DI DESTINAZIONE ESEGUIBILI FTCONTROLSMANAGER
rem DEL /F /Q "%FTCM_EXE_DESTINATION_FOLDER%\*.*"

IF %MAIN_TARGET_INTERNAL% == 11-10 (
	COPY "%FTCM_TEMPLATE_INI_FOLDER%\FTControlsManager.ini" "%FTCM_EXE_DESTINATION_FOLDER%\FTCONTROLSMANAGER.INI.%FTCM_VERSIONE%"
)

IF %MAIN_TARGET_INTERNAL% == 11-4 (
	COPY "%FTCM_TEMPLATE_INI_FOLDER%\FTControlsManager.ini" "%FTCM_EXE_DESTINATION_FOLDER%\FTCONTROLSMANAGER.INI.%FTCM_VERSIONE%"
)

REM pause