
SET DEVEXPRESS_VERSION=v19.2
SET DEVEXPRESS_FOLDER=C:\Program Files (x86)\DevExpress 19.2\Components\Bin\Framework

XCOPY /S /I "%DEVEXPRESS_FOLDER%\de" "%DEPENDENCIES_FOLDER%\de" /Y
XCOPY /S /I "%DEVEXPRESS_FOLDER%\ru" "%DEPENDENCIES_FOLDER%\ru" /Y
XCOPY /S /I "%DEVEXPRESS_FOLDER%\ja" "%DEPENDENCIES_FOLDER%\ja" /Y
XCOPY /S /I "%DEVEXPRESS_FOLDER%\es" "%DEPENDENCIES_FOLDER%\es" /Y


copy "%DEVEXPRESS_FOLDER%\DevExpress.Charts.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.CodeParser.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"	
copy "%DEVEXPRESS_FOLDER%\DevExpress.Data.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.DataAccess.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.DataAccess.%DEVEXPRESS_VERSION%.UI.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Diagram.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Images.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Office.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Pdf.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.PivotGrid.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Printing.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.RichEdit.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.RichEdit.%DEVEXPRESS_VERSION%.Export.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Sparkline.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Spreadsheet.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Utils.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Utils.%DEVEXPRESS_VERSION%.UI.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.Xpo.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraBars.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraCharts.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraCharts.%DEVEXPRESS_VERSION%.Extensions.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraCharts.%DEVEXPRESS_VERSION%.UI.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraCharts.%DEVEXPRESS_VERSION%.Wizard.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraDiagram.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraEditors.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraGauges.%DEVEXPRESS_VERSION%.Core.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraGauges.%DEVEXPRESS_VERSION%.Win.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraGrid.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraLayout.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraNavBar.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraPivotGrid.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraPrinting.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraReports.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraReports.%DEVEXPRESS_VERSION%.Extensions.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraRichEdit.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraSpreadsheet.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraTreeList.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"
copy "%DEVEXPRESS_FOLDER%\DevExpress.XtraVerticalGrid.%DEVEXPRESS_VERSION%.dll" "%DEPENDENCIES_FOLDER%"