REM =========================================
REM script di esecuzione in modalità standalone di TDK in modalità DESIGN su PLATFORM x86
REM =========================================

SET TEMP_DRIVE_LETTER=K:
NET USE %TEMP_DRIVE_LETTER% \\VBOXSRV\C_DRIVE

SET ROOT_MOUNTPOINT=%TEMP_DRIVE_LETTER%\GIT

SET ROOT_FOLDER=%ROOT_MOUNTPOINT%\bitbucket-ft\BuildSystem
SET BATCH_FOLDER=%ROOT_FOLDER%\src
SET ROOT_MOUNTPOINT_COMMON=%TEMP_DRIVE_LETTER%\GIT

MKDIR "%BATCH_FOLDER%\log"

SET LOG_FILE=%ROOT_FOLDER%\src\log\SETUP_FTCM_12_standalone.LOG
SET LOG_FILE_ERR=%ROOT_FOLDER%\src\log\SETUP_FTCM_ERR_12_standalone.LOG
SET VB6_OUTPUT=D:\FTCONTROLSMANAGER
SET FTSHUTDOWN_OUTPUT_FOLDER=D:\FTCONTROLSMANAGER\FTSYSTEMSHUTDOWN
SET VERSIONE=101.0.0.0
SET VERSIONE_WITH_TEXT=101.0.0.0-standalone
SET PATH_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBUILD.EXE
SET STANDALONE=0
SET MAIN_TARGET=12
SET CONFIGURATION=Release

REM cancella i files di LOG
ECHO Inizializzazione dei files di log 1> %LOG_FILE% 2> %LOG_FILE_ERR%

DEL /S C:\FTSystem\Bin\ /Q >> %LOG_FILE% 2>> %LOG_FILE_ERR%

SET BUILD_ERROR=0

CALL "%BATCH_FOLDER%\common\42_init.BAT" FEEDZ

call "%BATCH_FOLDER%\builders\build-deploy-FTLIBSERVICE-RELEASE" %ROOT_MOUNTPOINT% %ROOT_MOUNTPOINT_COMMON% "%PATH_MSBUILD%" >> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=FTLIBSERVICE
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
	EXIT /B
)

call "%BATCH_FOLDER%\builders\build-deploy-RDP-RELEASE.bat" %ROOT_MOUNTPOINT% %ROOT_MOUNTPOINT_COMMON% "%PATH_MSBUILD%" >> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=RDP
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
)

call "%BATCH_FOLDER%\builders\build-deploy-TCPIP-RELEASE.bat" %ROOT_MOUNTPOINT% %ROOT_MOUNTPOINT_COMMON% "%PATH_MSBUILD%" >> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=TCP/IP
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
)

call "%BATCH_FOLDER%\builders\build-deploy-FTSYSTEMSHUTDOWN-RELEASE.bat" %BATCH_FOLDER% %ROOT_MOUNTPOINT% %ROOT_MOUNTPOINT_COMMON% "%PATH_MSBUILD%" %FTSHUTDOWN_OUTPUT_FOLDER% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=FTSYSTYEMSHUTDOWN
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
)

call "%BATCH_FOLDER%\builders\build-TDK-DESIGN.bat" %ROOT_MOUNTPOINT% %PATH_MSBUILD% 1>> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=TDK-DESIGN
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
)

call "%BATCH_FOLDER%\builders\build-OVERLORD.bat" %VERSIONE_WITH_TEXT% %VERSIONE% %ROOT_MOUNTPOINT% %VB6_OUTPUT% %STANDALONE% %MAIN_TARGET% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=OVERLORD
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
)

call "%BATCH_FOLDER%\builders\build-DEVICEDRIVER-RELEASE.bat" %CONFIGURATION% %ROOT_MOUNTPOINT% %ROOT_MOUNTPOINT_COMMON% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

IF %BUILD_ERROR% == 1 (
	SET MODULE_ERROR=DEVICEDRIVER
	CALL "%BATCH_FOLDER%\common\banner_error.bat"
)

NET USE %TEMP_DRIVE_LETTER% /DELETE

PAUSE