REM =========================================
REM script di esecuzione in modalità TEST
REM =========================================

SET TEMP_DRIVE_LETTER=K:
NET USE %TEMP_DRIVE_LETTER% \\VBOXSRV\C_DRIVE

SET ROOT_MOUNTPOINT=%TEMP_DRIVE_LETTER%\GIT

SET ROOT_FOLDER=%ROOT_MOUNTPOINT%\bitbucket-ft\BuildSystem
SET BATCH_FOLDER=%ROOT_FOLDER%\src
SET ROOT_MOUNTPOINT_COMMON=%TEMP_DRIVE_LETTER%\GIT

MKDIR "%BATCH_FOLDER%\log"

SET LOG_FILE=%ROOT_FOLDER%\src\log\FTCM_12_test_RDP.LOG
SET LOG_FILE_ERR=%ROOT_FOLDER%\src\log\SETUP_FTCM_ERR_12_test_RDP.LOG
SET VB6_OUTPUT=D:\FTCONTROLSMANAGER
SET FTSHUTDOWN_OUTPUT_FOLDER=D:\FTCONTROLSMANAGER\FTSYSTEMSHUTDOWN
SET VERSIONE=101.0.0.0
SET VERSIONE_WITH_TEXT=101.0.0.0-standalone
SET PATH_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBUILD.EXE
SET STANDALONE=0
SET MAIN_TARGET=12
SET CONFIGURATION=Release

REM cancella i files di LOG
ECHO Inizializzazione dei files di log 1> %LOG_FILE% 2> %LOG_FILE_ERR%

DEL /S C:\FTSystem\Bin\ /Q >> %LOG_FILE% 2>> %LOG_FILE_ERR%

CALL "%BATCH_FOLDER%\common\42_init.BAT"

call "%BATCH_FOLDER%\builders\build-deploy-RDP-RELEASE.bat" %ROOT_MOUNTPOINT% %ROOT_MOUNTPOINT_COMMON% "%PATH_MSBUILD%" >> %LOG_FILE% 2>> %LOG_FILE_ERR%

NET USE %TEMP_DRIVE_LETTER% /DELETE

PAUSE