REM =========================================
REM 23-07-2018, rilascio non ufficiale per QCS
SET VERSIONE=11.5.24.1
REM =========================================

SET RILASCIO_UFFICIALE=0

REM CREAZIONE DIRECTORY PER I BINARY PRODOTTI

REM MAPPING TEMPORANEO PER UAC
REM ATTENZIONE, DEVE ESISTERE LO SHARE QUI SOTTO INDICATO - DA DEFINIRE IN VIRTUAL BOX COME DIRECTORY DI MACCHINA
NET USE Z: \\VBOXSRV\C_DRIVE

REM UNITA LOGICA CHE VIENE USATA COME PUNTO DI INGRESSO, USUALMENTE è Z: E VIENE MONTATO CON ISTRUZIONE "NET USE" IN QUESTO STESSO BATCH
REM VIENE QUI MONTATO PERCHE' DEVE ESSERE VISIBILE COME UAC - QUESTI SCRIPT VENGONO ESEGUITI CON PRIVILEGI UAC PER MOTIVI DI REGISTRAZIONI OGGETTI COM
SET ROOT_MOUNTPOINT=Z:

SET ROOT_FOLDER=%ROOT_MOUNTPOINT%\GIT\FT10-Setup-Sourcetree

SET BATCH_FOLDER=%ROOT_FOLDER%\Batch
SET BIN_FTCM=%ROOT_FOLDER%\Exe_non_ufficiali
SET BIN_TDK=%ROOT_FOLDER%\TheDarkKnight_non_ufficiali
SET BIN_DEPENDENCIES=%ROOT_FOLDER%\dependencies
SET RDP_FOLDER=%ROOT_FOLDER%\RDP\2.0.0
SET TCPIP_FOLDER=%ROOT_FOLDER%\TCPIP\4.0.0
SET RFID_FOLDER=%ROOT_FOLDER%\RFID\1.3.0
SET LOG_FILE=%ROOT_FOLDER%\Batch\SETUP.LOG
SET LOG_FILE_ERR=%ROOT_FOLDER%\Batch\SETUP_ERR.LOG
SET VERSIONE_WITH_TEXT=%VERSIONE%-develop

SET BRANCH_TO_CHECKOUT=develop

REM cancella i files di LOG
ECHO Inizializzazione dei files di log 1> %LOG_FILE% 2> %LOG_FILE_ERR%

rem GOTO :TEST_RDP_FEATURE

RMDIR /Q /S "%BIN_DEPENDENCIES%"

IF NOT EXIST "%BIN_FTCM%" MKDIR "%BIN_FTCM%"
IF NOT EXIST "%BIN_TDK%" MKDIR "%BIN_TDK%"
IF NOT EXIST "%BIN_DEPENDENCIES%" MKDIR "%BIN_DEPENDENCIES%"
IF NOT EXIST "%RDP_FOLDER%" MKDIR "%RDP_FOLDER%"
IF NOT EXIST "%TCPIP_FOLDER%" MKDIR "%TCPIP_FOLDER%"
IF NOT EXIST "%RFID_FOLDER%" MKDIR "%RFID_FOLDER%"
 
REM PULISCE LE CARTELLE IN CUI VERRANNO COPIATI I FILES
 
DEL "%BATCH_FOLDER%\SETUP.LOG" /Q 1>> %LOG_FILE% 2>> %LOG_FILE_ERR%
 
DEL "%BATCH_FOLDER%\SETUP_ERR.LOG" /Q 1>> %LOG_FILE% 2>> %LOG_FILE_ERR%

DEL "%BIN_DEPENDENCIES%\*.*" /Q /F 1>> %LOG_FILE% 2>> %LOG_FILE_ERR%
 
DEL "%BIN_FTCM%\%VERSIONE%\*.*" /Q /F 1>> %LOG_FILE% 2>> %LOG_FILE_ERR%

DEL "%BIN_TDK%\%VERSIONE%\*.*" /Q /F 1>> %LOG_FILE% 2>> %LOG_FILE_ERR%

REM =========================================

:TEST_FTLIBSERVICE_FEATURE

call "%BATCH_FOLDER%\build-deploy-FTLIBSERVICE-RELEASE" %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_SMARTPCSDLL_FEATURE

rem call "%BATCH_FOLDER%\build-SMARTPCSDLL-RELEASE.bat" %BATCH_FOLDER% %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_DESIGNTDK_FEATURE

call "%BATCH_FOLDER%\build-TDK-DESIGN.bat" %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_COPYDEPENDENCIES_FEATURE

call "%BATCH_FOLDER%\copy-DEPENDENCIES.bat" %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_RDP_FEATURE

call "%BATCH_FOLDER%\build-deploy-RDP-RELEASE.bat" %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_TCPIP_FEATURE

call "%BATCH_FOLDER%\build-deploy-TCPIP-RELEASE.bat" %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_FTSYSTEMSHUTDOWN_FEATURE

call "%BATCH_FOLDER%\build-deploy-FTSYSTEMSHUTDOWN-RELEASE.bat" %BATCH_FOLDER% %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_BUILDOVERLORD_FEATURE

call "%BATCH_FOLDER%\build-OVERLORD ver-NON-ufficiale.bat" %VERSIONE% %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_TDKBUILDRELEASE_FEATURE

call "%BATCH_FOLDER%\build-TDK-RELEASE.bat" %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_COPYFTCMDLL_FEATURE

call "%BATCH_FOLDER%\copy-FTCMDLL VER-NON-UFFICIALE.bat" %VERSIONE% %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_SETUP_FEATURE

CALL "%BATCH_FOLDER%\setup-TDK-RELEASE.bat" %VERSIONE% %RILASCIO_UFFICIALE% %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

rem pause

:TEST_ZIP_FEATURE

SET EXE_PDB_FOLDER=%BIN_FTCM%\%VERSIONE%\*.PDB
SET FTCM_PDB_FOLDER=%BIN_TDK%\%VERSIONE%\*.PDB
SET ZIP_FILENAME=FTCM_PDB_%VERSIONE%.ZIP

call "%BATCH_FOLDER%\zip-pdb-files.bat" %VERSIONE% %RILASCIO_UFFICIALE% %ZIP_FILENAME% %FTCM_PDB_FOLDER% %EXE_PDB_FOLDER% %ROOT_MOUNTPOINT% >> %LOG_FILE% 2>> %LOG_FILE_ERR%

REM RIMOZIONE MAPPING TEMPORANEO
NET USE Z: /DELETE

PAUSE
